/*
This procedure is to comapre all column in two tables for to 

*/

CREATE OR REPLACE PROCEDURE COLCOMPARE(KEY_ID VARCHAR2(200 CHAR))
AS
CURSOR TABLECURSOR IS 
SELECT A.TABLESOURCE, A.TABLENAME, A.TABLESCHEMA, A.TABLEKEYS, B.COLUMNLIST --COLUMNLIST IS CSV
, B.TABLESCHEMA
FROM TABLELIST TL 
INNER JOIN COLUMNLIST CL 
ON TL.TABLEID = CL.TABLEID
;

BEGIN
	FOR C IN TABLECURSOR 
	LOOP
		BEGIN

		EXECUTE IMMEDIATE 'CREATE TABLE '||A.TABLENAME||' AS '
		||CHAR 10|| 'SELECT * FROM '||A.TABLESOURCE||'.'||A.TABLENAME||'@DBLINK;' --DEFINE DB LINK IN MAIN

		EXECUTE IMMEDIATE 'DROP TABLE COLRESULTS'

		EXECUTE IMMEDIATE 'CREATE TABLE COLRESULTS AS'
		||CHAR 10|| 'WITH TABLEDATA AS '
		||CHAR 10|| '(SELECT DB1 AS TABLESOURCE, '||B.COLUMNLIST|| ', '||A.TABLESCHEMA||' SCHEMA '
		||CHAR 10|| ' WHERE '
		||CHAR 10|| 'UNION ALL'
		||CHAR 10|| 'SELECT DB2 AS TABLESOURCE, '||B.COLUMNLIST|| ', '||B.TABLESCHEMA||' SCHEMA'
		||CHAR 10|| 'WHERE 1=1' --APPLY ANY OTHER CONDITION
		||CHAR 10|| ')'

		||CHAR 10|| 'SELECT MIN(TABLESOURCE), MIN(SCHEMA)'
		||CHAR 10|| 'FROM TABLEDATA T '
		||CHAR 10|| 'GROUP BY ' ||B.COLUMNLIST||
		||CHAR 10|| 'HAVING COUNT(*) <> 2'
		||CHAR 10|| 'OR MIN(TABLESOURCE) = MAX(TABLESOURCE)'

		EXECUTE IMMEDIATE 'UPDATE COLRESULTS '
		||CHAR 10|| 'SET COUNTS = (SELECT COUNT(*) FROM COLRESULTS '
		||CHAR 10|| 'DUPLICATES = (SELECT COUNT(*) FROM '
		||CHAR 10|| '(SELECT * FROM COLRESULTS GROUP BY TABLESOURCE, '||B.COLUMNLIST||' HAVING COUNT(*) > 1)'

		END;
	LOOP END;
END;

