/*
This procedure is to comapre all column in two tables for to 

*/

CREATE OR REPLACE PROCEDURE COLCOMPARE(KEY_ID VARCHAR2(200 CHAR))
AS
CURSOR TABLECURSOR IS 
SELECT A.TABLESOURCE, A.TABLENAME, A.TABLESCHEMA, A.TABLEKEYS, B.COLUMNLIST --COLUMNLIST IS CSV
, B.TABLESCHEMA, TL.TABLEID, 
FROM TABLELIST TL 
INNER JOIN MUTUALCOL B 
ON TL.TABLEID = B.TABLEID
INNER JOIN TABLENAME A
ON TL.TABLEID = A.TABLEID
;

BEGIN
	FOR C IN TABLECURSOR 
	LOOP
		BEGIN

		EXECUTE IMMEDIATE 'CREATE TABLE '||A.TABLENAME||' AS '
		||CHR(10)|| 'SELECT * FROM '||A.TABLESOURCE||'.'||A.TABLENAME||'@DBLINK;' --DEFINE DB LINK IN MAIN

		EXECUTE IMMEDIATE 'DROP TABLE COLRESULTS'

		EXECUTE IMMEDIATE 'CREATE TABLE COLRESULTS AS'
		||CHR(10)|| 'WITH TABLEDATA AS '
		||CHR(10)|| '(SELECT DB1 AS TABLESOURCE, '||B.COLUMNLIST|| ', '||A.TABLESCHEMA||' SCHEMA '
		||CHR(10)|| ' WHERE '
		||CHR(10)|| 'UNION ALL'
		||CHR(10)|| 'SELECT DB2 AS TABLESOURCE, '||B.COLUMNLIST|| ', '||B.TABLESCHEMA||' SCHEMA'
		||CHR(10)|| 'WHERE 1=1' --APPLY ANY OTHER CONDITION
		||CHR(10)|| ')'

		||CHR(10)|| 'SELECT MIN(TABLESOURCE), MIN(SCHEMA)'
		||CHR(10)|| 'FROM TABLEDATA T '
		||CHR(10)|| 'GROUP BY ' ||B.COLUMNLIST||
		||CHR(10)|| 'HAVING COUNT(*) <> 2'
		||CHR(10)|| 'OR MIN(TABLESOURCE) = MAX(TABLESOURCE)'

		EXECUTE IMMEDIATE 'UPDATE COLRESULTS '
		||CHR(10)|| 'SET COUNTS = (SELECT COUNT(*) FROM COLRESULTS '
		||CHR(10)|| 'DUPLICATES = (SELECT COUNT(*) FROM '
		||CHR(10)|| '(SELECT * FROM COLRESULTS GROUP BY TABLESOURCE, '||B.COLUMNLIST||' HAVING COUNT(*) > 1)'

		END;
	LOOP END;
END;

